import React, { useState } from "react";
import { DocumentDuplicateIcon, DocumentPlusIcon, LinkIcon } from "./icons";

/**
 * The example traces shipped in website/public.
 *
 * Filenames are not arbitrary: `unified_parse` only accepts basenames starting
 * with `dedicated_log_triton_trace_`, so these stay in that shape to remain
 * re-parseable by the CLI after a user downloads one. They are regenerated by
 * `make regen-examples-install`.
 */
const BUNDLED_EXAMPLES = [
  {
    fileName: "dedicated_log_triton_trace_findhao__mapped.ndjson.gz",
    title: "Triton Example",
    description:
      "Hand-written kernels: an autotuned matmul and a fused elementwise op, with launch diffs, roofline and autotune sessions.",
  },
  {
    fileName: "dedicated_log_triton_trace_inductor__mapped.ndjson.gz",
    title: "Inductor Example",
    description:
      "Kernels torch.compile generated across two frames. Their Python source is inductor's output_code.py. No launch data yet.",
  },
] as const;

interface WelcomeScreenProps {
  loadBundledExample: (fileName: string) => void;
  handleFileSelected: (file: File) => void;
  openUrlInput: () => void;
}

/**
 * Welcome screen component shown when no data is loaded
 */
const WelcomeScreen: React.FC<WelcomeScreenProps> = ({ loadBundledExample, handleFileSelected, openUrlInput }) => {
  const [isDragOver, setIsDragOver] = useState(false);

  // Handle file input change
  const handleFileChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const files = e.target.files;
    if (files && files.length > 0) {
      const file = files[0];

      // Support NDJSON, gzip-compressed, or CLP files only
      const fileName = file.name.toLowerCase();
      const isValidFile =
        fileName.endsWith(".ndjson") ||
        fileName.endsWith(".gz") ||
        fileName.endsWith(".clp");

      if (isValidFile) {
        handleFileSelected(file);
      }
    }
  };

  // Handle drag and drop events
  const handleDragOver = (e: React.DragEvent) => {
    e.preventDefault();
    e.stopPropagation();
    setIsDragOver(true);
  };

  const handleDragLeave = (e: React.DragEvent) => {
    e.preventDefault();
    e.stopPropagation();
    setIsDragOver(false);
  };

  const handleDrop = (e: React.DragEvent) => {
    e.preventDefault();
    e.stopPropagation();
    setIsDragOver(false);

    const files = e.dataTransfer.files;
    if (files && files.length > 0) {
      const file = files[0];

      // Support NDJSON, gzip-compressed files, or CLP archives only
      const fileName = file.name.toLowerCase();
      const isValidFile =
        fileName.endsWith(".ndjson") ||
        fileName.endsWith(".gz") ||
        fileName.endsWith(".clp");

      if (isValidFile) {
        handleFileSelected(file);
      }
    }
  };

  return (
    <div className="flex flex-col items-center justify-center px-4 py-16 max-w-4xl mx-auto text-center">
      <h2 className="text-2xl font-bold text-gray-800 mb-6">Welcome to TritonParse</h2>
      <p className="mb-8 text-gray-600">
        Load a Triton log file to analyze compiled kernels and their IR representations. Supports NDJSON,
        gzip-compressed files, or CLP archives.
      </p>

      {/* Bundled example cards. Both files are produced by
          `make regen-examples-install`; the filenames are fixed by the
          trace-log naming convention the parser requires. */}
      <div className="grid grid-cols-1 sm:grid-cols-2 gap-6 w-full max-w-4xl mb-6">
        {BUNDLED_EXAMPLES.map((example) => (
          <button
            type="button"
            key={example.fileName}
            className="w-full bg-white p-6 rounded-lg shadow-sm border border-gray-200 hover:shadow-md transition-shadow cursor-pointer focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-blue-500"
            onClick={() => loadBundledExample(example.fileName)}
          >
            <span className="bg-blue-50 p-3 rounded-full w-12 h-12 flex items-center justify-center mx-auto mb-4">
              <DocumentDuplicateIcon aria-hidden="true" className="h-6 w-6 text-blue-500" />
            </span>
            <span className="block text-lg font-medium text-gray-800 mb-2">
              {example.title}
            </span>
            <span className="block text-sm text-gray-600">{example.description}</span>
          </button>
        ))}
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 gap-8 w-full max-w-4xl mb-10">
        {/* Local File Card */}
        <div
          className={`bg-white p-6 rounded-lg shadow-sm border border-gray-200 relative h-52 transition-all duration-200 ${isDragOver ? 'border-green-400 bg-green-200' : ''
            }`}
          onDragOver={handleDragOver}
          onDragLeave={handleDragLeave}
          onDrop={handleDrop}
        >
          <div className="bg-green-50 p-3 rounded-full w-12 h-12 flex items-center justify-center mx-auto mb-4">
            <DocumentPlusIcon aria-hidden="true" className="h-6 w-6 text-green-500" />
          </div>
          <h3 className="text-lg font-medium text-gray-800 mb-2">Local File</h3>
          <p className="text-sm text-gray-600 mb-4">
            {isDragOver ? 'Drop Triton log file here' : 'Open or drag a Triton log file (NDJSON, .gz or .clp)'}
          </p>
          <label htmlFor="welcomeFileInput" className="absolute inset-0 cursor-pointer" aria-label="Open local file" />
          <input
            type="file"
            id="welcomeFileInput"
            accept=".clp,.gz,.ndjson,application/gzip,application/x-ndjson"
            onChange={handleFileChange}
            className="hidden"
          />
        </div>

        {/* Remote URL Card */}
        <div
          className="bg-white p-6 rounded-lg shadow-sm border border-gray-200 hover:shadow-md transition-shadow"
          onClick={openUrlInput}
          style={{ cursor: "pointer" }}
        >
          <div className="bg-purple-50 p-3 rounded-full w-12 h-12 flex items-center justify-center mx-auto mb-4">
            <LinkIcon aria-hidden="true" className="h-6 w-6 text-purple-500" />
          </div>
          <h3 className="text-lg font-medium text-gray-800 mb-2">Remote URL</h3>
          <p className="text-sm text-gray-600">Load a Triton log file from a URL</p>
        </div>
      </div>

      <div className="text-sm text-gray-500 max-w-2xl">
        <h4 className="font-medium mb-2">About TritonParse</h4>
        <p>
          TritonParse helps you analyze Triton GPU kernels by visualizing the compilation process across different IR
          stages.
        </p>
      </div>
    </div>
  );
};

export default WelcomeScreen;
